apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-staging
  namespace: argocd
spec:
  project: devops-training
  source:
    repoURL: https://github.com/Oomaxime/devops-learning.git
    targetRevision: main
    path: gitops/apps/devops-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
